### ISSUE TITLE
SystemError: opening file "/tmp/str_walk.txt": No such file or directory

### ISSUE THREAD

**Issue by marcinkruk232** [network-embeddings/LightGraphsEmbeddings.jl#1]
Hey, when I try to use the function learn_embeddings(), I run into the following error:
_"SystemError: opening file "/tmp/str_walk.txt": No such file or directory"_

I followed the example you provided and this error occured. And even if I try to use it with literally any arguments, for example _learn_embeddings([1,2,3])_, the same error occurs. What might be the reason for that? The other two functions in the package seem to run without errors. I'm using Julia 1.5.3. This is the full stacktrace:
![image](https://user-images.githubusercontent.com/38554812/115995738-bb60bf00-a5dc-11eb-90ba-862c88868ea2.png)

**Comment by ollin18** [comment]
Thanks for pointing this out. The Word2Vec package (https://github.com/JuliaText/Word2Vec.jl) is only available for UNIX-like systems and Node2Vec.jl depends heavily on it. You could try with Docker or WSL.
